apiVersion: v1
kind: Service
metadata:
  name: workflow1
  namespace: namespace-workflow-1706525946982
spec:
  type: LoadBalancer
  selector:
    app: workflow1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000